### ISSUE TITLE
Julia 0.6 compatibility

### ISSUE THREAD

**Issue by mhinsch** [dennisprangle/ABCDistances.jl#2]
The package generates a lot of deprecation warnings on Julia 0.6.

I have fixed all of them in my own fork, however without any regards to backwards compatibility to Julia versions < 0.6. If that is acceptable for the official version I can issue a pull request.

**Comment by dennisprangle** [comment]
Yes please issue a pull request. Thanks for taking the time to fix the warnings!

**Comment by dennisprangle** [comment]
Fixed by beb5a5116
